use_frameworks!

platform :ios, '9.0'

target 'MyHightLightButton_Example' do
  pod 'MyHightLightButton', :path => '../'

  target 'MyHightLightButton_Tests' do
    inherit! :search_paths

    
  end
end
